CREATE TABLE posts (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id   UUID        NOT NULL,
    title       TEXT        NOT NULL,
    body        TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tags (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT   NOT NULL UNIQUE
);

CREATE TABLE post_tags (
    post_id  BIGINT NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    tag_id   BIGINT NOT NULL REFERENCES tags  (id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);
