[package]
name = "itx-compute-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = { version = "0.9" }
subst = "0.3.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }

itx-contract = { path = "../itx-contract" }
itx-impl = { path = "../itx-impl" }
