services:
  postgres:
    image: postgres:18.4-alpine@sha256:96d56f7f57c6aacd1fcb908bc83b345ec5f83231ee486dd66a1baadce274db88
    restart: always
    ports:
      - "127.0.0.1:0:5432"
    environment:
      POSTGRES_DB: itx-db
      POSTGRES_USER: itx-admin
      POSTGRES_PASSWORD: "itx-admin"
    command:
      - "-c"
      - "log_statement=all"

  postgres-init:
    image: flyway/flyway:12-alpine@sha256:72098336aa1248f248cb1d1ad2f82cf2e6a61a7a82c113505a369a1397226ec2
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - type: bind
        source: ../storage/postgres/sql
        target: /flyway/sql
    command:
      - "-url=jdbc:postgresql://postgres:5432/itx-db"
      - "-user=itx-admin"
      - "-password=itx-admin"
      - "-locations=filesystem:/flyway/sql"
      - "-connectRetries=15"
      - "migrate"

  mariadb:
    image: mariadb:12.2@sha256:350261292d0129fd4b24f537dcf05ecd3ebe34d39d5b592af551f38310e7a167
    restart: always
    ports:
      - "127.0.0.1:0:3306"
    environment:
      MARIADB_DATABASE: itx-db
      MARIADB_USER: itx-admin
      MARIADB_PASSWORD: "itx-admin"
      MARIADB_ROOT_PASSWORD: "itx-admin"
    command:
      - "--general-log=1"
      - "--general-log-file=/var/log/mysql/general.log"

  mariadb-init:
    image: flyway/flyway:12-alpine@sha256:72098336aa1248f248cb1d1ad2f82cf2e6a61a7a82c113505a369a1397226ec2
    depends_on:
      - mariadb
    restart: on-failure
    volumes:
      - type: bind
        source: ../storage/mariadb/sql
        target: /flyway/sql
    command:
      - "-url=jdbc:mariadb://mariadb:3306/itx-db"
      - "-user=itx-admin"
      - "-password=itx-admin"
      - "-locations=filesystem:/flyway/sql"
      - "-connectRetries=15"
      - "migrate"

  sqs:
    image: softwaremill/elasticmq-native:latest@sha256:e4580ab9ad1bd5cd37b4ba04911bc5ccc8cd2d9ab4de56ece65acee71c24e05c
    restart: always
    ports:
      - "127.0.0.1:0:9324"
      - "127.0.0.1:0:9325"
    volumes:
      - type: bind
        source: ./docker/elasticmq.conf
        target: /opt/elasticmq.conf

  sqs-ui:
    image: softwaremill/elasticmq-ui:latest@sha256:549f467ed95d7465cb471b43cd01a8691f5ac0fa5debc0d49ba65a73341c07fb
    ports:
      - "127.0.0.1:0:3000"
    environment:
      SQS_ENDPOINT: http://sqs:9324
    depends_on:
      - sqs

  rabbitmq:
    image: rabbitmq:4-management-alpine@sha256:eb70bd64440624f8a7b93f619d28900865330996a3204aec97852bbe4bb77573
    restart: always
    ports:
      - "127.0.0.1:0:5672"
      - "127.0.0.1:0:15672"
    environment:
      RABBITMQ_DEFAULT_USER: itx-admin
      RABBITMQ_DEFAULT_PASS: itx-admin
    volumes:
      - type: bind
        source: ./docker/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./docker/rabbitmq-definitions.json
        target: /etc/rabbitmq/definitions.json