services:
  postgres:
    image: postgres:18.6-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    restart: always
    ports:
      - "127.0.0.1:0:5432"
    environment:
      POSTGRES_DB: itx-db
      POSTGRES_USER: itx-admin
      POSTGRES_PASSWORD: "itx-admin"
    command:
      - "-c"
      - "log_statement=all"

  postgres-init:
    image: flyway/flyway:13-alpine@sha256:e51c63b766e54fdc5e08778018746cb0071643a8b898ca15a2cf8df268ddb584
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - type: bind
        source: ../storage/postgres/sql
        target: /flyway/sql
    command:
      - "-url=jdbc:postgresql://postgres:5432/itx-db"
      - "-user=itx-admin"
      - "-password=itx-admin"
      - "-locations=filesystem:/flyway/sql"
      - "-connectRetries=15"
      - "migrate"

  mariadb:
    image: mariadb:12.3@sha256:c237fd50cc48d6f2b87c4ca66d52f3b5eef7271b3bea7aee586c0be19d5b460d
    restart: always
    ports:
      - "127.0.0.1:0:3306"
    environment:
      MARIADB_DATABASE: itx-db
      MARIADB_USER: itx-admin
      MARIADB_PASSWORD: "itx-admin"
      MARIADB_ROOT_PASSWORD: "itx-admin"
    command:
      - "--general-log=1"
      - "--general-log-file=/var/log/mysql/general.log"

  mariadb-init:
    image: flyway/flyway:13-alpine@sha256:e51c63b766e54fdc5e08778018746cb0071643a8b898ca15a2cf8df268ddb584
    depends_on:
      - mariadb
    restart: on-failure
    volumes:
      - type: bind
        source: ../storage/mariadb/sql
        target: /flyway/sql
    command:
      - "-url=jdbc:mariadb://mariadb:3306/itx-db"
      - "-user=itx-admin"
      - "-password=itx-admin"
      - "-locations=filesystem:/flyway/sql"
      - "-connectRetries=15"
      - "migrate"

  sqs:
    image: softwaremill/elasticmq-native:latest@sha256:e4580ab9ad1bd5cd37b4ba04911bc5ccc8cd2d9ab4de56ece65acee71c24e05c
    restart: always
    ports:
      - "127.0.0.1:0:9324"
      - "127.0.0.1:0:9325"
    volumes:
      - type: bind
        source: ./docker/elasticmq.conf
        target: /opt/elasticmq.conf

  sqs-ui:
    image: softwaremill/elasticmq-ui:latest@sha256:549f467ed95d7465cb471b43cd01a8691f5ac0fa5debc0d49ba65a73341c07fb
    ports:
      - "127.0.0.1:0:3000"
    environment:
      SQS_ENDPOINT: http://sqs:9324
    depends_on:
      - sqs

  rabbitmq:
    image: rabbitmq:4-management-alpine@sha256:073c89fec6c7504703a2a709817578b2569114394c6107f6e1250681a9451a6e
    restart: always
    ports:
      - "127.0.0.1:0:5672"
      - "127.0.0.1:0:15672"
    environment:
      RABBITMQ_DEFAULT_USER: itx-admin
      RABBITMQ_DEFAULT_PASS: itx-admin
    volumes:
      - type: bind
        source: ./docker/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./docker/rabbitmq-definitions.json
        target: /etc/rabbitmq/definitions.json